### ISSUE TITLE
Don't close issues until they are *fixed*.

### ISSUE THREAD

**Issue by jelkner** [Ahmad-Ali123/website#5]
You marked the issue about adding a link to your gdw work as closed, but when I visit your homepage this is what I see:

![homepage_ahmad_2021-11-15](https://user-images.githubusercontent.com/819114/141781569-c0414c07-4d76-4e04-899b-8ef5b07d8e00.png)

Please don't close an issue until it is actually fixed.

**Comment by Ahmad-Ali123** [comment]
ok now my Index or homepage should be fixed
